name: CI Workflow

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # или любая другая поддерживаемая версия

      # Шаг 3: Установка зависимостей и запуск тестов
      - name: Install dependencies and run tests
        run: |
          npm ci
          npm test

      # Шаг 4: Запуск кастомного экшена (строго после тестов)
      - name: Say hello from hexlet
        uses: hexlet-components/hello-from-hexlet-action@release
